# Generated by Django 4.1.6 on 2023-03-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_categories_user_task_category_task_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='description',
            field=models.CharField(default='All tasks related to work, like sending emails, scheduling meetings with clients etc.', max_length=255),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(default='work', max_length=255, unique=True),
        ),
    ]
