# Generated by Django 4.1.6 on 2023-03-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_categories_description_alter_categories_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(default='work', max_length=50, unique=True),
        ),
    ]
