# Generated by Django 4.1.6 on 2023-03-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_categories_color_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='description',
            field=models.CharField(default='This can include tasks related to your job or career, such as deadlines, meetings, projects, and tasks that you need to complete for work.', max_length=255),
        ),
    ]
