# Generated by Django 4.1.6 on 2023-03-02 03:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0006_alter_categories_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(default='work', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='categories',
            unique_together={('name', 'user')},
        ),
    ]
