# Generated by Django 4.1.6 on 2023-02-28 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0002_rename_statuses_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='status',
            table='statuses',
        ),
    ]
